// 실제 PostgreSQL WASM 엔진 검증. Supabase HTTP/Storage/Realtime 전체 검증은 아니다.
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const runtime=process.env.REGISTRY_PG_RUNTIME;
if (!runtime) throw new Error('REGISTRY_PG_RUNTIME 임시 npm 설치 경로가 필요합니다.');
const {PGlite}=await import(pathToFileURL(path.join(runtime,'node_modules/@electric-sql/pglite/dist/index.js')).href);
const {pgcrypto}=await import(pathToFileURL(path.join(runtime,'node_modules/@electric-sql/pglite/dist/contrib/pgcrypto.js')).href);
const pg=new PGlite({extensions:{pgcrypto}});
await pg.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;create schema storage;create schema extensions;
create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
create publication supabase_realtime;
create table privacy_purge_log(id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id),resource_kind text check(resource_kind in ('consent-form','data-collect')),resource_id uuid,record_count integer,file_count integer,purged_at timestamptz default now());`);
for(const file of ['202608120001_registry_sign.sql','202608130001_registry_auth_and_public_api.sql','202608200001_registry_field_value_encryption.sql','202610010200_registry_io_and_atomic_submission.sql']) await pg.exec(await readFile(`supabase/migrations/${file}`,'utf8'));
await pg.exec('grant usage on schema public,auth to authenticated,anon,service_role;grant all on all tables in schema public to authenticated,service_role;');
const q=async(sql,params=[]) => (await pg.query(sql,params)).rows;
const scalar=async(sql,params=[]) => Object.values((await q(sql,params))[0])[0];
const owner='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002';
await q('insert into auth.users(id) values($1),($2)',[owner,other]);
const [r]=await q("insert into registries(owner_id,mode,title,allow_walk_in,retention_months) values($1,'fixed','가상 DB 검증',true,3) returning *",[owner]);
await q("insert into registry_columns(registry_id,key,label,position) values($1,'aff','소속',0) returning *",[r.id]);
await q("insert into registry_participants(registry_id,row_number,name,field_values_ciphertext) select $1,n,'가상교사'||n,'encrypted-fixture' from generate_series(1,1500) n",[r.id]);
let checks=0;const pass=(name)=>{checks++;console.log('PASS '+name);};
const snapshot=await scalar('select registry_owner_snapshot($1,$2)',[r.id,owner]);assert.equal(snapshot.participants.length,1500);assert.equal(snapshot.registry.password_digest,undefined);assert.equal(snapshot.participants[0].verification_digest,undefined);pass('snapshot preserves 1500 rows and strips digests');
assert.equal(await scalar('select registry_owner_snapshot($1,$2)',[r.id,other]),null);pass('foreign owner snapshot denied');
await pg.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${other}',false);`);assert.equal((await q('select * from registry_owner_summaries()')).length,0);
await pg.exec(`select set_config('request.jwt.claim.sub','${owner}',false);`);assert.equal((await q('select * from registry_owner_summaries()'))[0].participant_count,1500);await pg.exec('reset role');pass('owner summary RLS');
assert.equal(await scalar("select has_function_privilege('anon','registry_commit_signature(uuid,uuid,text,uuid,uuid,timestamptz,text,text,text,text,text,integer,integer,text,boolean)','EXECUTE')"),false);pass('anonymous commit RPC denied');
const participants=snapshot.participants;
for(let i=0;i<60;i++){const ctx=await scalar("select registry_public_context($1,'submit','shared-school-ip','', '',$2)",[r.public_token,participants[i].id]);assert.equal(ctx.error,undefined);}pass('60 participants from same school IP admitted');
for(let i=0;i<12;i++) await scalar("select registry_public_context($1,'submit','shared-school-ip','', '',$2)",[r.public_token,participants[100].id]);assert.equal((await scalar("select registry_public_context($1,'submit','shared-school-ip','', '',$2)",[r.public_token,participants[100].id])).status,429);pass('per participant abuse limit');
await scalar('select registry_set_verification_code($1,$2,$3,$4)',[r.id,participants[101].id,owner,'123456']);
for(let i=0;i<12;i++) assert.equal((await scalar("select registry_public_context($1,'search','badcode-ip','','가상교사102',null,'000000')",[r.public_token])).error,undefined);
assert.equal((await scalar("select registry_public_context($1,'search','badcode-ip','','가상교사102',null,'000000')",[r.public_token])).status,429);
const correct=await scalar("select registry_public_context($1,'search','badcode-ip','','가상교사102',null,'123456')",[r.public_token]);assert.equal(correct.participants.length,1);assert.equal(correct.participants[0].verification_digest,undefined);pass('failed code counter, correct search and digest redaction');
const submitWrong=await scalar("select registry_public_context($1,'submit','wrong-submit-code','','',$2,'000000')",[r.public_token,participants[101].id]);assert.equal(submitWrong.status,401);pass('issued code required for submission');
const [capacity]=await q("insert into registries(owner_id,mode,title) values($1,'fixed','가상 정원 검사') returning *",[owner]);
assert.equal((await scalar('select registry_owner_add_participant($1,$2,$3,$4)',[capacity.id,other,'가상교사','cipher'])).status,404);
const added=await scalar('select registry_owner_add_participant($1,$2,$3,$4)',[capacity.id,owner,'가상교사','cipher']);assert.equal(added.participant.rowNumber,1);
await q("insert into registry_participants(registry_id,row_number,name) select $1,n,'가상'||n from generate_series(2,2000) n",[capacity.id]);
assert.equal((await scalar('select registry_owner_add_participant($1,$2,$3,$4)',[capacity.id,owner,'정원초과','cipher'])).status,422);pass('owner atomic addition, ownership and 2000 participant cap');
await pg.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${owner}',false);`);const newToken=await scalar('select rotate_registry_token($1)',[capacity.id]);await pg.exec('reset role');assert.notEqual(newToken,capacity.public_token);assert.equal((await scalar("select registry_public_context($1,'metadata','rotated-old')",[capacity.public_token])).status,404);pass('token rotation invalidates old public context');
const target=participants[0],req=crypto.randomUUID();
const args=[r.id,r.public_token,'',target.id,req,target.updated_at,null,'ciphertext-new','draw',`${r.id}/${target.id}/${req}.png`,'imagehash',600,200,'requestdigest',false];
const commitSql='select registry_commit_signature('+args.map((_,i)=>'$'+(i+1)).join(',')+')';
await pg.exec("create function fail_signature_update() returns trigger language plpgsql as $$begin if new.status='signed' then raise exception 'fault injection';end if;return new;end$$;create trigger fail_signature_update before update on registry_participants for each row execute function fail_signature_update();");
await assert.rejects(()=>scalar(commitSql,args));assert.equal(await scalar('select count(*) from registry_signatures where participant_id=$1',[target.id]),0);assert.equal(await scalar('select status from registry_participants where id=$1',[target.id]),'pending');pass('SQL exception rolls back signature and participant together');await pg.exec('drop trigger fail_signature_update on registry_participants');
assert.equal((await scalar(commitSql,args)).ok,true);const [saved]=await q('select status,field_values,field_values_ciphertext from registry_participants where id=$1',[target.id]);assert.deepEqual(saved,{status:'signed',field_values:null,field_values_ciphertext:'ciphertext-new'});assert.equal((await scalar(commitSql,args)).replayed,true);const changed=[...args];changed[13]='different-requestdigest';assert.equal((await scalar(commitSql,changed)).status,409);pass('atomic save, exact replay and changed retry rejection');
const before=await scalar('select count(*) from registry_participants where registry_id=$1',[r.id]);await scalar("select registry_public_context($1,'walk-in','walkin-ip','','가상신규')",[r.public_token]);assert.equal(await scalar('select count(*) from registry_participants where registry_id=$1',[r.id]),before);pass('walk-in preview creates no rows');
const walk=[...args];walk[3]=crypto.randomUUID();walk[4]=crypto.randomUUID();walk[5]=null;walk[6]='가상신규';walk[9]=`${r.id}/${walk[3]}/${walk[4]}.png`;assert.equal((await scalar(commitSql,walk)).ok,true);assert.equal(await scalar('select status from registry_participants where id=$1',[walk[3]]),'signed');pass('walk-in creates participant only at final atomic submission');
await q("update registries set password_digest=crypt($2,gen_salt('bf')) where id=$1",[r.id,'correct']);for(let i=0;i<10;i++)assert.equal((await scalar("select registry_public_context($1,'unlock','badpw-ip','wrong')",[r.public_token])).status,401);assert.equal((await scalar("select registry_public_context($1,'unlock','badpw-ip','wrong')",[r.public_token])).status,429);assert.equal((await scalar("select registry_public_context($1,'unlock','badpw-ip','correct')",[r.public_token])).error,undefined);pass('failed password counter and correct retry');
await q("update registries set status='closed' where id=$1",[r.id]);assert.ok(await scalar('select closed_at from registries where id=$1',[r.id]));assert.equal((await scalar(commitSql,walk)).status,409);await q("update registries set status='open' where id=$1",[r.id]);assert.equal(await scalar('select closed_at from registries where id=$1',[r.id]),null);pass('close denies submission and reopen resets retention start');
await q("update registries set status='closed' where id=$1",[r.id]);const counts=before+1;
assert.equal((await scalar('select registry_prepare_purge($1,$2,$3,2,2)',[r.id,owner,counts-1])).status,409);assert.equal((await scalar('select registry_prepare_purge($1,$2,$3,2,2)',[r.id,owner,counts])).ok,true);await assert.rejects(()=>q("update registries set status='open' where id=$1",[r.id]));await assert.rejects(()=>q("insert into registry_participants(registry_id,row_number,name) values($1,2000,'가상변경')",[r.id]));pass('purge verifies counts and locks reopen/roster changes');
assert.equal((await scalar('select registry_finish_purge($1,$2,$3,2)',[r.id,owner,counts])).ok,true);assert.equal(await scalar('select count(*) from registries where id=$1',[r.id]),0);assert.equal(await scalar("select record_count from privacy_purge_log where resource_kind='registry'"),counts);pass('purge DB transaction and non-identifying audit');
console.log(JSON.stringify({engine:'PGlite PostgreSQL with pgcrypto',checks,limitations:['No Supabase Auth/Storage/Realtime gateway','No multi-connection concurrency verification']}));await pg.close();
