import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import {jsPDF} from 'jspdf';
import pg from './.runtime/node_modules/pg/lib/index.js';
const base='design/consent-implementation/2026-10-01';const cfg=JSON.parse(await readFile(base+'/.runtime/local.json','utf8'));
const pool=new pg.Pool({host:'127.0.0.1',port:55432,user:'postgres',password:'isolated-consent-test',database:'consent_test'});
const db=createClient('http://127.0.0.1:55434',cfg.service,{auth:{persistSession:false,autoRefreshToken:false}});
const api=async(body)=>{const res=await fetch('http://127.0.0.1:55434/functions/v1/consent-forms-admin',{method:'POST',headers:{Authorization:'Bearer '+cfg.teacher,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(`${res.status} ${result.error}`);return result;};
const checks=[];const test=async(name,fn)=>{await fn();checks.push({name,result:'pass'});console.log('PASS',name);};
const choice={id:'participation',label:'참가 여부',mode:'single',required:true,minSelections:1};
const fields=[{id:'opinion',kind:'text',label:'보호자 의견',required:true,pageIndex:0,x:10,y:30,width:40,height:5},
 {id:'yes',kind:'checkbox',label:'동의',required:false,choice,pageIndex:0,x:10,y:45,width:3,height:2},
 {id:'no',kind:'checkbox',label:'비동의',required:false,choice,pageIndex:0,x:35,y:45,width:3,height:2},
 {id:'signature',kind:'signature',label:'보호자 서명',required:false,pageIndex:1,x:10,y:30,width:30,height:10}];
const pdf=new jsPDF({unit:'mm',format:'a4'});pdf.text('Fictional School Notice - no real student data',20,25);pdf.text('Opinion:',21,86);pdf.rect(21,89.1,84,14.85);pdf.text('Agree',30,137);pdf.text('Decline',82,137);pdf.text('Original text below opinion box stays visible.',20,113);pdf.addPage();pdf.text('Signature on page two',20,25);
const source=Buffer.from(pdf.output('arraybuffer'));await writeFile(base+'/evidence/fictional-source.pdf',source);
const createForm=async(title,size=0,password='')=>{const id=randomUUID();const path=`${cfg.user}/${id}/${randomUUID()}.pdf`;const upload=await db.storage.from('consent-documents').upload(path,source,{contentType:'application/pdf'});assert.equal(upload.error,null);
 const inserted=await db.from('consent_forms').insert({id,owner_id:cfg.user,title,file_name:'fictional-source.pdf',source_path:path,fields,page_count:2,page_sizes:[{width:210,height:297},{width:210,height:297}],recipient_mode:size?'named':'open',allow_resubmission:true,retention_months:3}).select('id,public_token').single();assert.equal(inserted.error,null);
 const people=Array.from({length:size},(_,i)=>({id:randomUUID(),name:i===0?'가상학생 긴 이름 가나다라마바사':'가상학생 '+String(i+1).padStart(4,'0'),studentKey:String(i+1).padStart(2,'0')}));
 await api({action:'finalize',formId:id,recipients:people,password});
 const recipients=(await pool.query('select id,token from consent_recipients where form_id=$1 order by created_at,id',[id])).rows;
 return {id,token:inserted.data.public_token,recipients,fields};};
const integrity=await createForm('DB 무결성 검증 자료',1);const person=integrity.recipients[0];
const commit=async({requestId=randomUUID(),digest='same',recipientToken=person.token,expected=null,signatures=[],revision=1}={})=>(await pool.query('select public.commit_consent_response($1,$2,$3,$4,$5,$6,$7,$8,$9) as result',[integrity.token,recipientToken,randomUUID(),requestId,digest,'sealed-test-payload',JSON.stringify(signatures),revision,expected])).rows[0].result;
let first;
await test('동일 요청 8개 동시 제출은 응답 1개로 커밋',async()=>{const requestId=randomUUID();const results=await Promise.all(Array.from({length:8},()=>commit({requestId})));assert.equal(new Set(results.map(r=>r.responseId)).size,1);assert.equal(results.filter(r=>!r.replayed).length,1);first=results[0].responseId;assert.equal((await pool.query('select response_count,current_response_count from consent_forms where id=$1',[integrity.id])).rows[0].response_count,1);});
await test('다른 두 화면 재제출은 하나만 성공하고 오래된 화면은 409',async()=>{const results=await Promise.allSettled([commit({expected:first}),commit({expected:first})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/409/);});
const latest=(await pool.query('select response_id from consent_recipients where id=$1',[person.id])).rows[0].response_id;
await test('서명 메타데이터 실패 시 응답·명단 포인터·카운터 전체 롤백',async()=>{await assert.rejects(()=>commit({expected:latest,signatures:[{field_id:'wrong',storage_path:'wrong'}]}),/400/);assert.deepEqual((await pool.query('select response_count,current_response_count from consent_forms where id=$1',[integrity.id])).rows[0],{response_count:2,current_response_count:1});assert.equal((await pool.query('select response_id from consent_recipients where id=$1',[person.id])).rows[0].response_id,latest);});
await test('원본 수정·오래된 문서 제출·활성 수합 파기 차단',async()=>{await assert.rejects(()=>pool.query("select save_consent_form($1,$2,'{\"fields\":[]}'::jsonb)",[integrity.id,cfg.user]),/409/);await assert.rejects(()=>commit({expected:latest,revision:99}),/409/);await assert.rejects(()=>pool.query('select begin_consent_purge($1,$2,2)',[integrity.id,cfg.user]),/409/);});
await test('최신 결과 1개와 제출 이력 2개를 별도 보존',async()=>{assert.equal((await pool.query('select count(*)::int as n from consent_current_responses where form_id=$1',[integrity.id])).rows[0].n,1);assert.equal((await pool.query('select count(*)::int as n from consent_responses where form_id=$1',[integrity.id])).rows[0].n,2);});
await test('다른 교사 RLS 및 직접 수정/RPC 권한 우회 차단',async()=>{const client=await pool.connect();try{await client.query('begin');await client.query('set local role authenticated');await client.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:'22222222-2222-4222-8222-222222222222'})]);assert.equal((await client.query('select * from consent_forms where id=$1',[integrity.id])).rows.length,0);assert.equal((await client.query('update consent_forms set title=$2 where id=$1 returning id',[integrity.id,'forbidden'])).rows.length,0);assert.equal((await client.query("select has_function_privilege('authenticated','public.commit_consent_response(uuid,uuid,uuid,uuid,text,text,jsonb,integer,uuid)','execute') as allowed")).rows[0].allowed,false);await client.query('rollback');}finally{client.release();}});
await test('파기 수량 변경·파기 중 재개 차단, 행과 감사 기록 원자적 삭제',async()=>{await pool.query("select save_consent_form($1,$2,'{\"status\":\"closed\"}'::jsonb)",[integrity.id,cfg.user]);await assert.rejects(()=>pool.query('select begin_consent_purge($1,$2,1)',[integrity.id,cfg.user]),/409/);await pool.query('select begin_consent_purge($1,$2,2)',[integrity.id,cfg.user]);await assert.rejects(()=>pool.query("select save_consent_form($1,$2,'{\"status\":\"open\"}'::jsonb)",[integrity.id,cfg.user]),/409/);const result=await api({action:'purge',formIds:[integrity.id],expectedCounts:{[integrity.id]:2}});assert.equal(result.failed.length,0);assert.equal((await pool.query('select * from consent_forms where id=$1',[integrity.id])).rows.length,0);assert.equal((await pool.query('select record_count from privacy_purge_log where resource_id=$1',[integrity.id])).rows[0].record_count,2);});
const forms={empty:await createForm('Chrome 빈 응답 검증'),class24:await createForm('Chrome 24명 수합 검증',24),class60:await createForm('Chrome 60명 수합 검증',60),max:await createForm('Chrome 최대 2000명 검증',2000),password:await createForm('Chrome 비밀번호 검증',1,'test-pass')};
await test('명단 재저장은 개인 토큰과 변경 없는 암호문을 보존',async()=>{const before=(await pool.query('select id,token,identity_ciphertext,xmin::text from consent_recipients where form_id=$1 order by id',[forms.class24.id])).rows;const all=await api({action:'list',formId:forms.class24.id});await api({action:'replace',formId:forms.class24.id,recipients:all.recipients.map(p=>({id:p.id,name:p.name,studentKey:p.studentKey}))});const after=(await pool.query('select id,token,identity_ciphertext,xmin::text from consent_recipients where form_id=$1 order by id',[forms.class24.id])).rows;assert.deepEqual(before,after);});
await test('관리 첫 조회는 60명과 응답 헤더만, 응답 본문/서명 URL 제외',async()=>{const bundle=await api({action:'bundle',formId:forms.max.id});assert.equal(bundle.recipients.length,60);assert.equal(bundle.form.recipient_count,2000);assert.ok(!('password_digest'in bundle.form));const second=await api({action:'list',formId:forms.max.id,cursor:{at:bundle.recipients.at(-1).createdAt,id:bundle.recipients.at(-1).id}});assert.equal(second.recipients.length,60);assert.equal(new Set([...bundle.recipients,...second.recipients].map(r=>r.id)).size,120);});
// 시험용 명단의 식별자와 공개 토큰은 runtime 안에만 저장한다.
await writeFile(base+'/.runtime/fixtures.json',JSON.stringify(forms));
const report={postgres:(await pool.query('select version()')).rows[0].version,migrationSha256:createHash('sha256').update(await readFile('supabase/migrations/202610011000_consent_integrity_io.sql')).digest('hex'),checks};await writeFile(base+'/evidence/db-verification.json',JSON.stringify(report,null,2));await pool.end();console.log('DB_CHECKS',checks.length);
