create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claims',true)::json->>'sub','')::uuid$$;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb, unique(bucket_id,name));alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $$select (string_to_array(name,'/'))[1:array_length(string_to_array(name,'/'),1)-1]$$;
create schema extensions;create publication supabase_realtime;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant select,insert,update,delete on tables to authenticated;
grant usage on schema public,storage,auth,extensions to anon,authenticated,service_role;
grant all on all tables in schema storage to service_role;grant select,insert,update,delete on storage.objects to authenticated;
create table public.data_collections(id uuid primary key,status text,updated_at timestamptz);
