import {beforeEach,describe,expect,it,vi} from 'vitest';
import {addConsentLocalDraft,addConsentLocalResponse,deleteConsentLocalDraft,getConsentLocalDraft,listConsentLocalHistory,listConsentLocalRecipients,listConsentLocalResponses,saveConsentLocalRecipients,updateConsentLocalDraft} from '../../src/features/consentForms/consentFormsLocalStore';
import type {ConsentLocalDraft} from '../../src/features/consentForms/types';
const form:ConsentLocalDraft={id:'form',title:'가상 수합',fileName:'fictional.pdf',fieldCount:1,recipientMode:'named',recipientCount:1,createdAt:'2026-10-01',description:'',fields:[],publicToken:'public',deadline:'',passwordEnabled:false,passwordHash:'',allowResubmission:true,responseCount:0,status:'open'};
beforeEach(()=>{const entries=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>entries.get(k)??null,setItem:(k:string,v:string)=>entries.set(k,v)});addConsentLocalDraft({...form});saveConsentLocalRecipients(form.id,[{id:'person',name:'가상학생',identifier:'01'}]);});
describe('수합의 최신 응답과 이력',()=>{
 it('재시도는 같은 응답, 재제출은 이력만 늘리고 최신 결과 한 건을 남긴다',()=>{const person=listConsentLocalRecipients(form.id)[0];const first=addConsentLocalResponse(form.id,{opinion:'이전'},person.token,'request1',null);expect(addConsentLocalResponse(form.id,{opinion:'이전'},person.token,'request1',null).id).toBe(first.id);addConsentLocalResponse(form.id,{opinion:'최신'},person.token,'request2',first.id);expect(listConsentLocalResponses(form.id)).toHaveLength(1);expect(listConsentLocalResponses(form.id)[0].values.opinion).toBe('최신');expect(listConsentLocalHistory(form.id,person.id)).toHaveLength(2);expect(getConsentLocalDraft(form.id)?.responseCount).toBe(2);expect(getConsentLocalDraft(form.id)?.currentResponseCount).toBe(1);});
 it('개인 링크 오류를 익명 제출로 바꾸지 않는다',()=>{expect(()=>addConsentLocalResponse(form.id,{opinion:'가상'},'broken')).toThrow('개인 링크');expect(listConsentLocalResponses(form.id)).toHaveLength(0);});
 it('이전 응답을 연 다른 화면의 늦은 재제출을 거절한다',()=>{const p=listConsentLocalRecipients(form.id)[0];addConsentLocalResponse(form.id,{opinion:'최신'},p.token,'one',null);expect(()=>addConsentLocalResponse(form.id,{opinion:'늦은 응답'},p.token,'two',null)).toThrow('다른 화면');expect(getConsentLocalDraft(form.id)?.responseCount).toBe(1);});
 it('응답을 받은 원본 변경과 진행 중 파기를 차단한다',()=>{addConsentLocalResponse(form.id,{opinion:'가상'});expect(()=>updateConsentLocalDraft(form.id,{fields:[]})).toThrow('원본과 필드');expect(()=>deleteConsentLocalDraft(form.id)).toThrow('진행 중');updateConsentLocalDraft(form.id,{status:'closed'});deleteConsentLocalDraft(form.id);expect(getConsentLocalDraft(form.id)).toBe(null);});
});
