import { AlertCircle, CheckCircle2, LockKeyhole, Send } from 'lucide-react';
import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { SignatureCanvas } from '../registry/SignatureCanvas';
import { countConsentLocalResponse, getConsentLocalDraftByToken, hashConsentPassword } from './consentFormsLocalStore';

export function PublicConsentResponsePage() {
  const { token = '' } = useParams();
  const draft = getConsentLocalDraftByToken(token);
  const [unlocked, setUnlocked] = useState(() => sessionStorage.getItem(`consent-unlocked:${token}`) === 'true');
  const [password, setPassword] = useState('');
  const [values, setValues] = useState<Record<string, string>>({});
  const [error, setError] = useState('');
  const [submitted, setSubmitted] = useState(false);

  if (!draft) return <main className="grid min-h-screen place-items-center bg-[#F6F8FB] p-5"><div className="w-full max-w-md border-y border-[#DCE3EA] bg-white px-6 py-12 text-center"><AlertCircle className="mx-auto h-8 w-8 text-[#B42318]" /><h1 className="mt-4 text-xl font-extrabold">가정통신문을 찾을 수 없습니다</h1><p className="mt-2 text-sm text-[#526174]">담당자에게 올바른 링크를 다시 요청해 주세요.</p></div></main>;
  const deadlinePassed = Boolean(draft.deadline && draft.deadline < new Date().toISOString().slice(0, 10));
  if (draft.status === 'closed' || deadlinePassed) return <main className="grid min-h-screen place-items-center bg-[#F6F8FB] p-5"><div className="w-full max-w-md border-y border-[#DCE3EA] bg-white px-6 py-12 text-center"><LockKeyhole className="mx-auto h-8 w-8 text-[#64748B]" /><h1 className="mt-4 text-xl font-extrabold">응답이 종료되었습니다</h1><p className="mt-2 text-sm text-[#526174]">추가 제출이 필요하면 담당자에게 문의해 주세요.</p></div></main>;

  if (draft.passwordEnabled && !unlocked) return <main className="grid min-h-screen place-items-center bg-[#F6F8FB] p-5"><form className="w-full max-w-md border-y border-[#DCE3EA] bg-white px-6 py-8" onSubmit={async (event) => { event.preventDefault(); if (await hashConsentPassword(password) !== draft.passwordHash) { setError('비밀번호가 맞지 않습니다.'); return; } sessionStorage.setItem(`consent-unlocked:${token}`, 'true'); setError(''); setUnlocked(true); }}><LockKeyhole className="h-8 w-8 text-[#0F6CBD]" /><h1 className="mt-4 text-xl font-extrabold">비밀번호 입력</h1><p className="mt-2 text-sm text-[#526174]">담당자에게 받은 비밀번호를 입력하세요.</p><label className="mt-6 block text-sm font-bold">공개 링크 비밀번호<input type="password" autoFocus value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 min-h-[48px] w-full rounded-lg border border-[#C8D0DA] px-3 font-normal" /></label>{error ? <p role="alert" className="mt-3 text-sm font-semibold text-[#B42318]">{error}</p> : null}<button type="submit" className="mt-5 min-h-[48px] w-full rounded-lg bg-[#0F6CBD] text-sm font-bold text-white">확인</button></form></main>;

  if (submitted) return <main className="grid min-h-screen place-items-center bg-[#F6F8FB] p-5"><div className="w-full max-w-md border-y border-[#DCE3EA] bg-white px-6 py-12 text-center"><CheckCircle2 className="mx-auto h-11 w-11 text-[#126B32]" /><h1 className="mt-5 text-2xl font-extrabold">응답을 제출했습니다</h1><p className="mt-2 text-sm text-[#526174]">담당자에게 응답 완료 상태가 전달됩니다.</p></div></main>;

  return <main className="min-h-screen bg-[#F6F8FB] px-4 py-8 sm:py-12"><form className="mx-auto w-full max-w-xl border-y border-[#DCE3EA] bg-white px-5 py-7 sm:px-7" onSubmit={(event) => { event.preventDefault(); const missing = draft.fields.find((field) => field.required && !values[field.id]); if (missing) { setError(`${missing.label} 항목을 입력해 주세요.`); return; } countConsentLocalResponse(draft.id); setSubmitted(true); }}><p className="text-xs font-bold text-[#0F6CBD]">가정통신문 응답</p><h1 className="mt-2 text-2xl font-extrabold">{draft.title}</h1>{draft.description ? <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#526174]">{draft.description}</p> : null}<div className="mt-7 space-y-6">{draft.fields.map((field) => field.kind === 'checkbox' ? <label key={field.id} className="flex min-h-[48px] items-start gap-3 border-y border-[#EEF1F4] py-3 text-sm font-bold"><input type="checkbox" checked={values[field.id] === 'true'} onChange={(event) => setValues({ ...values, [field.id]: event.target.checked ? 'true' : '' })} className="mt-0.5 h-5 w-5 shrink-0 accent-[#0F6CBD]" /><span>{field.label}{field.required ? <span className="ml-1 text-[#B42318]">*</span> : null}</span></label> : <div key={field.id}><label className="block text-sm font-bold">{field.label}{field.required ? <span className="ml-1 text-[#B42318]">*</span> : null}{field.kind === 'text' ? <input value={values[field.id] ?? ''} onChange={(event) => setValues({ ...values, [field.id]: event.target.value })} className="mt-2 min-h-[48px] w-full rounded-lg border border-[#C8D0DA] px-3 font-normal" /> : field.kind === 'date' ? <input type="date" value={values[field.id] ?? ''} onChange={(event) => setValues({ ...values, [field.id]: event.target.value })} className="mt-2 min-h-[48px] w-full rounded-lg border border-[#C8D0DA] px-3 font-normal" /> : <span className="mt-2 block"><SignatureCanvas onChange={(dataUrl) => setValues((current) => ({ ...current, [field.id]: dataUrl ?? '' }))} /></span>}</label></div>)}</div>{error ? <p role="alert" className="mt-5 text-sm font-semibold text-[#B42318]">{error}</p> : null}<button type="submit" className="mt-7 inline-flex min-h-[52px] w-full items-center justify-center gap-2 rounded-lg bg-[#0F6CBD] text-base font-bold text-white"><Send className="h-5 w-5" />응답 제출</button></form></main>;
}
