// 관찰용 도구: 결함을 찾는 기대값을 포함한다. 통과가 제품 수정 성공을 뜻하지 않는다.
// 실행: node design/feature-reviews/2026-10-01-registry/observe.mjs
import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import writeXlsxFile from 'write-excel-file/node';
import readXlsxFile from 'read-excel-file/node';
import fs from 'node:fs/promises';
import path from 'node:path';

const base = process.env.REGISTRY_REVIEW_URL ?? 'http://127.0.0.1:4182';
const out = path.resolve('design/feature-reviews/2026-10-01-registry/evidence');
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const results = { chrome: await browser.version(), base, mode: 'local-demo / network-blocked-mock', observations: [], errors: [], blocked: [] };
const record = (name, detail) => { results.observations.push({ name, detail }); console.log(name, JSON.stringify(detail)); };
const context = await browser.newContext({ viewport: { width: 1366, height: 900 }, acceptDownloads: true, permissions: ['clipboard-read', 'clipboard-write'] });
await context.route('**/*', route => {
  if (route.request().url().startsWith(base + '/')) return route.continue();
  results.blocked.push(route.request().url().split('?')[0]);
  return route.abort();
});
const page = await context.newPage();
page.on('pageerror', error => results.errors.push(error.message));
const shot = async (name, p = page) => p.screenshot({ path: path.join(out, name + '.png'), fullPage: true });
const layout = async (p = page) => p.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, height: document.documentElement.scrollHeight }));
const axe = async (name, p = page, include = 'main') => {
  const r = await new AxeBuilder({ page: p }).include(include).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze();
  record(name, r.violations.map(v => ({ id: v.id, help: v.help, nodes: v.nodes.map(n => ({ target: n.target, failure: n.failureSummary })) })));
};
const next = () => page.getByRole('button', { name: '다음', exact: true }).click();
const download = async (label, filename) => {
  const waiting = page.waitForEvent('download');
  await page.getByRole('button', { name: label, exact: true }).click();
  const d = await waiting;
  await d.saveAs(path.join(out, filename));
  record('download:' + label, { suggested: d.suggestedFilename(), bytes: (await fs.stat(path.join(out, filename))).size });
};
const draw = async (p) => {
  const canvas = p.getByLabel('서명 입력 영역');
  await canvas.scrollIntoViewIfNeeded();
  const b = await canvas.boundingBox();
  await p.mouse.move(b.x + b.width * .15, b.y + b.height * .65);
  await p.mouse.down();
  await p.mouse.move(b.x + b.width * .4, b.y + b.height * .25, { steps: 8 });
  await p.mouse.move(b.x + b.width * .65, b.y + b.height * .65, { steps: 8 });
  await p.mouse.up();
};

try {
  await page.goto(base + '/tools/registry-sign');
  await page.evaluate(() => { localStorage.setItem('schooldoc_registry_v1', '[]'); sessionStorage.clear(); });
  await page.reload();
  await expect(page.getByRole('heading', { name: '등록부가 없습니다' })).toBeVisible();
  await shot('02-empty-list-desktop');
  await page.getByRole('button', { name: '새 등록부', exact: true }).click();
  await next();
  await expect(page.getByRole('alert')).toContainText('제목');
  await page.getByLabel(/문서 제목/).fill('가상 연수 등록부 리뷰');
  await page.getByLabel('왼쪽 내용').fill('일시: 2026. 10. 1.(목) 14:00');
  await page.getByLabel('오른쪽 내용').fill('장소: 가상학교 강당');
  await next();
  await page.getByLabel('1번 참석자 성명', { exact: true }).fill('가상수기참석자');
  await page.getByLabel('1번 참석자 소속', { exact: true }).fill('가상수기학교');
  await page.getByRole('button', { name: '이전', exact: true }).click();
  await next();
  await expect(page.getByLabel('1번 참석자 성명', { exact: true })).toHaveValue('가상수기참석자');
  record('manual-and-back-retains', true);
  // 화면 안내와 같은 소속[TAB]성명 형식에도 헤더는 데이터가 된다.
  await page.getByLabel(/표 붙여넣기/).fill('소속\t성명\n가상학교\t가상홍길동');
  await page.getByRole('button', { name: '명단 반영' }).click();
  record('paste-header-and-replacement', { first: await page.getByLabel('1번 참석자 성명', { exact: true }).inputValue(), second: await page.getByLabel('2번 참석자 성명', { exact: true }).inputValue(), rows: await page.locator('tbody tr').count(), confirmation: await page.getByRole('alertdialog').count() });
  await shot('03-paste-header-imported');
  const names = Array.from({ length: 24 }, (_, i) => i < 2 ? '가상김하늘' : `가상참석자${String(i + 1).padStart(2, '0')}`);
  const workbook = await writeXlsxFile([
    [{ value: '가상 연수 자료', type: String }], [],
    [{ value: '성 명', type: String }, { value: '학교명', type: String }],
    ...names.map((name, i) => [{ value: name, type: String }, { value: `가상학교 ${i + 1}반`, type: String }]),
  ]).toBuffer();
  await fs.writeFile(path.join(out, 'fictional-roster.xlsx'), workbook);
  await page.locator('input[type=file]').setInputFiles({ name: '가상명단.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: workbook });
  await expect(page.getByLabel('24번 참석자 성명', { exact: true })).toHaveValue('가상참석자24');
  await shot('04-excel-roster-desktop');
  await page.setViewportSize({ width: 390, height: 844 });
  await shot('05-roster-mobile');
  record('create-mobile-overflow', await layout());
  await page.setViewportSize({ width: 1366, height: 900 });
  await next();
  await page.getByRole('button', { name: '2단 20명', exact: true }).click();
  await shot('06-create-preview-desktop');
  record('create-preview-space', await page.getByRole('region', { name: '등록부 인쇄 미리보기' }).evaluate(e => { const child = e.querySelector('.registry-print-page'); return { region: e.getBoundingClientRect().height, page: child.getBoundingClientRect().height, scrollHeight: e.scrollHeight }; }));
  await next();
  await page.getByLabel(/공개 링크 비밀번호/).fill('fictional-pass');
  await shot('07-share-settings');
  await page.getByRole('button', { name: '등록부 생성', exact: true }).click();
  await expect(page.getByRole('heading', { name: '참석자 명단', exact: true })).toBeVisible();
  const manage = page.url();
  const publicUrl = await page.getByLabel('서명 링크 주소').inputValue();
  record('created', { manage, publicUrl, count: 24 });
  await page.getByRole('button', { name: '서명 링크 복사', exact: true }).click();
  record('clipboard', await page.evaluate(() => navigator.clipboard.readText()));
  await download('QR 이미지 저장', 'registry-qr.png');
  await shot('08-teacher-24-pending-desktop');
  await axe('axe-teacher');

  const participant = await context.newPage();
  participant.on('pageerror', e => results.errors.push(e.message));
  await participant.setViewportSize({ width: 390, height: 844 });
  await participant.goto(publicUrl);
  await participant.getByLabel('공개 링크 비밀번호').fill('wrong');
  await participant.getByRole('button', { name: '확인', exact: true }).click();
  await expect(participant.getByRole('alert')).toHaveText('비밀번호가 맞지 않습니다.');
  await shot('09-password-error-mobile', participant);
  await participant.getByLabel('공개 링크 비밀번호').fill('fictional-pass');
  await participant.getByRole('button', { name: '확인', exact: true }).click();
  await participant.getByLabel('이름 또는 소속 검색').fill('가상김하늘');
  const duplicates = participant.getByRole('button', { name: /선택/ });
  record('duplicate-identification-demo', await duplicates.allTextContents());
  await shot('10-duplicate-names-mobile', participant);
  await duplicates.first().focus();
  await participant.keyboard.press('Enter');
  await expect(participant.getByRole('dialog')).toBeVisible();
  await expect(participant.getByRole('button', { name: '서명 창 닫기' })).toBeFocused();
  const focusNames = [];
  for (let i = 0; i < 8; i++) { await participant.keyboard.press('Tab'); focusNames.push(await participant.evaluate(() => ({ tag: document.activeElement.tagName, name: document.activeElement.getAttribute('aria-label') || document.activeElement.textContent, inDialog: !!document.activeElement.closest('[role=dialog]') }))); }
  record('keyboard-focus-loop', focusNames);
  await participant.keyboard.press('Escape');
  await expect(duplicates.first()).toBeFocused();
  await duplicates.first().click();
  await shot('11-signature-dialog-mobile', participant);
  await axe('axe-signature-dialog', participant, '[role=dialog]');
  await draw(participant);
  const beforeResize = await participant.getByLabel('서명 입력 영역').evaluate(c => c.toDataURL());
  await participant.setViewportSize({ width: 844, height: 390 });
  await participant.waitForTimeout(150);
  record('canvas-rotation', await participant.getByLabel('서명 입력 영역').evaluate(c => {const data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return { width:c.width,height:c.height,inkPixels:Array.from(data).filter((v,i)=>i%4===3 && v>0).length };}));
  await participant.setViewportSize({ width: 390, height: 844 });
  await participant.waitForTimeout(150);
  await participant.getByRole('button', { name: '서명 제출', exact: true }).click();
  await expect(participant.getByRole('heading', { name: '서명이 제출되었습니다' })).toBeVisible();
  await shot('12-signature-success-mobile', participant);
  const signature = await page.evaluate(() => JSON.parse(localStorage.getItem('schooldoc_registry_v1'))[0].participants[0].signature.dataUrl);
  await fs.writeFile(path.join(out, 'signature-original.png'), Buffer.from(signature.split(',')[1], 'base64'));
  record('canvas-save-and-rotation-data', { beforeResizeBytes: beforeResize.length, savedBytes: signature.length });
  await page.reload();
  await expect(page.getByRole('row', { name: /1 가상김하늘/ }).getByText('완료', { exact: true })).toBeVisible();
  await shot('13-teacher-mixed-desktop');
  await page.getByRole('button', { name: '미서명', exact: true }).click();
  record('pending-filter', await page.locator('table').first().locator('tbody tr').count());
  await page.getByRole('button', { name: '완료', exact: true }).click();
  record('signed-filter', await page.locator('table').first().locator('tbody tr').count());
  await page.getByRole('button', { name: '전체', exact: true }).click();
  await download('엑셀 다운로드', 'registry-results.xlsx');
  record('exported-excel', (await readXlsxFile(path.join(out, 'registry-results.xlsx'))).slice(0, 4));
  await download('PDF 다운로드', 'registry-download.pdf');
  // 실제 Chrome 인쇄 엔진; 미리보기 한 페이지만 존재하는 상황.
  await page.pdf({ path: path.join(out, 'registry-browser-print.pdf'), format: 'A4', printBackground: true, preferCSSPageSize: true });
  record('print-DOM-page-count', await page.locator('.registry-print-page').count());
  await page.setViewportSize({ width: 390, height: 844 });
  await shot('14-teacher-mixed-mobile');
  record('teacher-mobile-overflow', await layout());
  await page.setViewportSize({ width: 1366, height: 900 });
  await page.evaluate(() => { document.documentElement.style.zoom = '2'; });
  await shot('15-teacher-css-200');
  record('teacher-css200-overflow', await layout());
  await page.evaluate(() => { document.documentElement.style.zoom = ''; });
  await participant.getByRole('button', { name: '다른 사람 서명하기', exact: true }).click();
  await participant.getByLabel('이름 또는 소속 검색').fill('가상김하늘');
  record('signed-public-blocked', await participant.getByRole('button', { name: /서명 완료/ }).count());
  await participant.evaluate(() => { document.documentElement.style.zoom = '2'; });
  await shot('16-public-css-200', participant);
  record('public-css200-overflow', await layout(participant));
  await participant.evaluate(() => { document.documentElement.style.zoom = ''; });
  await page.getByRole('button', { name: '가상김하늘 재서명', exact: true }).click();
  await shot('17-resign-confirmation');
  await page.getByRole('button', { name: '취소', exact: true }).click();
  await expect(page.getByRole('button', { name: '가상김하늘 재서명', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '가상김하늘 재서명', exact: true }).click();
  await page.getByRole('button', { name: '재서명 요청', exact: true }).click();
  await participant.reload();
  await participant.getByLabel('이름 또는 소속 검색').fill('가상김하늘');
  await participant.getByRole('button', { name: /선택/ }).first().click();
  await draw(participant);
  await participant.getByRole('button', { name: '서명 제출', exact: true }).click();
  await expect(participant.getByRole('heading', { name: '서명이 제출되었습니다' })).toBeVisible();
  record('teacher-requested-resign', true);
  await page.getByRole('button', { name: '수합 종료', exact: true }).click();
  await participant.reload();
  await expect(participant.getByText('서명 수합이 종료되었습니다.')).toBeVisible();
  await shot('18-closed-public-mobile', participant);
  await page.getByRole('button', { name: '다시 열기', exact: true }).click();
  record('close-reopen', true);
  // 긴 이름·4열 경계 자료와 500명은 별도 가상 seed. 생성 흐름 결과와 구분한다.
  const saved = await page.evaluate(() => localStorage.getItem('schooldoc_registry_v1'));
  await page.evaluate(() => {
    const r = JSON.parse(localStorage.getItem('schooldoc_registry_v1'))[0];
    r.columns = ['소속학교명', '학년반번호', '직위또는업무명', '추가확인사항'].map((label,i)=>({id:'field-'+i,label}));
    r.participants = Array.from({length:30},(_,i)=>({id:'boundary-'+i,rowNumber:i+1,name:i===0?'가상외국인참석자알렉산드리아긴성명테스트':'가상참석자'+(i+1),values:Object.fromEntries(r.columns.map(c=>[c.id,'가상학교 긴 추가항목 데이터 '+(i+1)]))}));
    r.layout=30;
    localStorage.setItem('schooldoc_registry_v1',JSON.stringify([r]));
  });
  await page.reload();
  await shot('19-boundary-four-columns');
  record('boundary-print-layout', await page.locator('.registry-print-page').evaluate(e => ({ page:e.getBoundingClientRect().toJSON(), table:e.querySelector('table').getBoundingClientRect().toJSON(), rows:Array.from(e.querySelectorAll('tbody tr')).map(r=>r.getBoundingClientRect().height), overflowing:Array.from(e.querySelectorAll('td,th')).filter(c=>c.scrollHeight>c.clientHeight+1||c.scrollWidth>c.clientWidth+1).map(c=>({text:c.textContent,width:c.clientWidth,scrollWidth:c.scrollWidth,height:c.clientHeight,scrollHeight:c.scrollHeight})), footer:e.lastElementChild.getBoundingClientRect().toJSON() })));
  await download('PDF 다운로드', 'registry-boundary-download.pdf');
  await page.evaluate(() => { const r=JSON.parse(localStorage.getItem('schooldoc_registry_v1'))[0];r.columns=[{id:'affiliation',label:'소속'}];r.participants=Array.from({length:500},(_,i)=>({id:'max-'+i,rowNumber:i+1,name:'가상참석자'+(i+1),values:{affiliation:'가상학교'+(i+1)}}));localStorage.setItem('schooldoc_registry_v1',JSON.stringify([r])); });
  await page.reload();
  await page.getByLabel('참석자 명단 페이지 선택').selectOption('10');
  await page.getByLabel('인쇄 미리보기 페이지 선택').selectOption('17');
  await shot('20-teacher-500-last-page');
  record('500-roster-paging', { renderedRows:await page.locator('table').first().locator('tbody tr').count(), printPages:await page.locator('.registry-print-page').count(), last:await page.locator('table').first().getByRole('row',{name:/500 가상참석자500/}).count() });
  await page.evaluate(raw=>localStorage.setItem('schooldoc_registry_v1',raw),saved);
  await page.goto(base+'/tools/registry-sign/new');
  await page.getByRole('button',{name:/현장 자율 입력/}).click();
  await page.getByLabel(/문서 제목/).fill('가상 자율 입력 등록부');
  await next();await next();await next();
  await page.getByRole('button',{name:'등록부 생성',exact:true}).click();
  await expect(page.getByRole('heading',{name:'참석자 명단',exact:true})).toBeVisible();
  await shot('21-custom-empty-teacher');
  const customUrl=await page.getByLabel('서명 링크 주소').inputValue();
  await participant.goto(customUrl);
  await participant.getByLabel('성명',{exact:true}).fill('가상현장참석자');
  await participant.getByLabel('소속',{exact:true}).fill('가상현장학교');
  await participant.getByRole('button',{name:'정보 확인 후 서명하기',exact:true}).click();
  await participant.getByRole('button',{name:'서명 창 닫기'}).click();
  record('custom-cancel-leaves-participant', await page.evaluate(()=>JSON.parse(localStorage.getItem('schooldoc_registry_v1')).find(r=>r.title==='가상 자율 입력 등록부').participants.length));
  await participant.getByRole('button',{name:'정보 확인 후 서명하기',exact:true}).click();
  await draw(participant);
  await participant.getByRole('button',{name:'서명 제출',exact:true}).click();
  await expect(participant.getByRole('heading',{name:'서명이 제출되었습니다'})).toBeVisible();
  await page.reload();
  await shot('22-custom-cancel-and-submit-teacher');
  record('custom-two-rows-after-cancel-submit', await page.locator('table').first().locator('tbody tr').allTextContents());
  await page.getByRole('button',{name:'등록부 목록',exact:true}).click();
  const del=page.getByRole('button',{name:'가상 자율 입력 등록부 삭제',exact:true});
  await del.focus();await page.keyboard.press('Enter');
  await expect(page.getByRole('button',{name:'취소',exact:true})).toBeFocused();
  await shot('23-delete-confirmation');
  await page.keyboard.press('Escape');await expect(del).toBeFocused();
  await del.click();await page.getByRole('button',{name:'등록부 삭제',exact:true}).click();
  await participant.goto(customUrl);
  await expect(participant.getByRole('heading',{name:'등록부를 찾을 수 없습니다'})).toBeVisible();
  record('demo-delete-invalidates-link', true);

  // 운영 UI 분기를 served module만 교체해서 검사. 제품 파일과 서버에는 쓰지 않는다.
  const mockContext=await browser.newContext({viewport:{width:390,height:844}});
  await mockContext.route('**/*',async route=>{
    const url=route.request().url();
    if (!url.startsWith(base+'/')) return route.abort();
    if (url.includes('/src/features/registry/registryConfig.ts')) return route.fulfill({contentType:'application/javascript',body:'export const isRegistryDemoMode = false;'});
    if (url.includes('/mock-supabase/')) return route.fulfill({status:200,contentType:'application/json',body:'{}'});
    return route.continue();
  });
  let searchFail=false, submitFail=true, walkInCalls=0;
  const calls=[];
  const token='22222222-2222-4222-8222-222222222222';
  const meta={id:'11111111-1111-4111-8111-111111111111',publicToken:token,title:'가상 모의 서버 등록부',leftHeader:'일시: 가상 검증',rightHeader:'장소: 가상학교',mode:'fixed',status:'open',layout:20,allowWalkIn:true,hasPassword:true,columns:[{id:'affiliation',label:'소속'}]};
  await mockContext.route('**/mock-supabase/functions/v1/registry-public',async route=>{
    const body=route.request().postDataJSON();calls.push({action:body.action,query:body.query,confirmDuplicate:body.confirmDuplicate});
    const send=(status,data)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
    if(body.action==='metadata')return send(200,{registry:meta});
    if(body.password!=='fictional-pass')return send(401,{error:'비밀번호가 맞지 않습니다.'});
    if(body.action==='unlock')return send(200,{ok:true});
    if(body.action==='search')return searchFail?send(500,{error:'참석자를 검색하지 못했습니다.'}):send(200,{participants:body.query==='가상학교'?[]:[1,2].map(i=>({id:`00000000-0000-4000-8000-00000000000${i}`,rowNumber:i,name:'가***늘',values:{affiliation:'가상****'},signed:false}))});
    if(body.action==='submit')return submitFail?send(500,{error:'서명 요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.'}):send(200,{ok:true});
    if(body.action==='walk-in'){walkInCalls++;return body.confirmDuplicate?send(200,{participants:[{id:'00000000-0000-4000-8000-000000000003',rowNumber:3,name:'가***자',values:{affiliation:'가상****'},signed:false}]}):send(200,{duplicateCount:1});}
    return send(400,{error:'모의 오류'});
  });
  const remote=await mockContext.newPage();
  remote.on('pageerror',e=>results.errors.push(e.message));
  await remote.goto(base+'/s/registry/'+token);
  await remote.getByLabel('공개 링크 비밀번호').fill('wrong');
  await remote.getByRole('button',{name:'확인',exact:true}).click();
  await expect(remote.getByRole('alert')).toContainText('맞지');
  await remote.getByLabel('공개 링크 비밀번호').fill('fictional-pass');
  await remote.getByRole('button',{name:'확인',exact:true}).click();
  await remote.getByLabel('이름 검색').fill('가상학교');
  await expect(remote.getByText('일치하는 참석자가 없습니다.')).toBeVisible();
  await shot('24-mock-affiliation-not-found',remote);
  await remote.getByLabel('이름 검색').fill('가상김하늘');
  await expect(remote.getByRole('button',{name:/가\*\*\*늘.*선택/})).toHaveCount(2);
  await shot('25-mock-duplicate-names',remote);
  await remote.getByRole('button',{name:/선택/}).first().click();
  await remote.getByRole('dialog').getByLabel('소속',{exact:true}).fill('가상수정학교');
  await draw(remote);
  await remote.getByRole('button',{name:'서명 제출',exact:true}).click();
  await expect(remote.getByRole('alert')).toContainText('처리하지');
  await shot('26-mock-submit-error-retains-ink',remote);
  record('mock-submit-error-preserves', {value:await remote.getByRole('dialog').getByLabel('소속',{exact:true}).inputValue(),enabled:await remote.getByRole('button',{name:'서명 제출',exact:true}).isEnabled()});
  submitFail=false;
  await remote.getByRole('button',{name:'서명 제출',exact:true}).click();
  await expect(remote.getByRole('heading',{name:'서명이 제출되었습니다'})).toBeVisible();
  record('mock-retry-success',true);
  await remote.getByRole('button',{name:'다른 사람 서명하기',exact:true}).click();
  await remote.getByLabel('이름 검색').fill('가상김하늘');
  await expect(remote.getByRole('button',{name:/선택/})).toHaveCount(2);
  searchFail=true;
  await remote.getByLabel('이름 검색').fill('가상홍길동');
  await expect(remote.getByRole('alert')).toContainText('검색하지');
  await shot('27-mock-stale-search-results',remote);
  record('stale-search-on-error',{query:await remote.getByLabel('이름 검색').inputValue(),buttons:await remote.getByRole('button',{name:/선택/}).allTextContents()});
  await remote.getByLabel('성명',{exact:true}).fill('가상현장참석자');
  await remote.getByLabel('소속',{exact:true}).fill('가상학교');
  await remote.getByRole('button',{name:'정보 확인 후 서명하기',exact:true}).click();
  await expect(remote.getByRole('alertdialog')).toBeVisible();
  await shot('28-mock-duplicate-walkin-confirm',remote);
  await remote.getByRole('button',{name:'취소',exact:true}).click();
  await remote.getByRole('button',{name:'정보 확인 후 서명하기',exact:true}).click();
  await remote.getByRole('button',{name:'동명이인으로 추가',exact:true}).click();
  await expect(remote.getByRole('dialog',{name:/님 서명/})).toBeVisible();
  record('mock-duplicate-walkin', {calls:walkInCalls,requests:calls});
  await remote.getByRole('button',{name:'서명 창 닫기'}).click();
  await axe('axe-public-mock',remote);
  // 자율 입력형에는 기존 미서명 현장 행으로 돌아가는 검색 경로가 없다.
  meta.mode='custom';
  await remote.reload();
  await remote.getByLabel('공개 링크 비밀번호').fill('fictional-pass');
  await remote.getByRole('button',{name:'확인',exact:true}).click();
  await remote.getByLabel('성명',{exact:true}).fill('가상현장참석자');
  await remote.getByRole('button',{name:'정보 확인 후 서명하기',exact:true}).click();
  await expect(remote.getByRole('alertdialog')).toBeVisible();
  await shot('34-mock-custom-duplicate-no-search',remote);
  record('custom-duplicate-has-no-search',{searchInputCount:await remote.getByLabel('이름 검색').count(),message:await remote.getByRole('alertdialog').innerText()});
  await mockContext.close();
} finally {
  await fs.writeFile(path.join(out,'observations.json'),JSON.stringify(results,null,2));
  await context.close();
  await browser.close();
}
